server:
  port: 8080

spring:
  application:
    name: product-portal-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres #jdbc:mysql://localhost:3306/product_portal
    username: postgres.oxqytdxpvqguetztwpxs #root
    password: databasePortalWebsiteAbc123!@# #1234
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: GMT+7

# app properties
cloudinary:
  name: dixswfj8d
  apiKey: 876943471796471
  apiSecret: XXlwrvw541Qmp83wIgDjxZpIoNQ
  rootFolder: product-portal-website-images
jwt:
  jwtSecret: ======================jwt=spring===========================
  jwtExpiration: 10 hour
  jwtRefreshExpiration: 15 hour